# Jekyll configuration for Weeka website
title: Weeka - Visual Weekly Planner for Families
description: Transform daily negotiations into visual agreements. A simple weekly planner that brings structure and fairness to family life.
url: "https://weeka.github.io"
baseurl: ""

# Build settings
markdown: kramdown

# Exclude files from build
exclude:
  - README.md
  - feature_img_resizer.sh